### ISSUE TITLE
Docker Setup very incomplete

### ISSUE THREAD

**Issue by darioackermann** [cloud-carbon-footprint/cloud-carbon-footprint#1262]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

(irrelevant for this issue)

### Expected Behavior

* When setting up the local client docker, when browsing the docker IP, the client should be displayed
* The client should connect to a (through env variables) specificable API

### Actual Behavior

* When browsing the exposed client, the default NGINX "it works" page is displayed
  * NGINX points by default to `/usr/share/`, although frontend files are in `/var/www`, 
* The client blindly tries to connect `/api/` on the same host. 
  

### To Reproduce

* Run the client docker image without any additonal settings and expose port 80
* Browse port 80 in your browser: You will see an "nginx - it works!" page

### Currently applied workaround

Easy fix:

#### docker-compose.yml
```yaml
  carbon-api:
    image: cloudcarbonfootprint/api
    restart: unless-stopped
    env_file:
      - services/ccf/.env

  carbon-client:
    image: xxx.dkr.ecr.eu-central-1.amazonaws.com/xxx
    build:
      context: ./services/ccf/
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=ccf.mydomain.com
 ```

#### ccf/Dockerfile

```yml
FROM cloudcarbonfootprint/client
COPY default.conf /etc/nginx/conf.d/default.conf
```

#### default.conf 
```yml
server {
  listen        80;
  listen   [::]:80;
  location / {
    root    /var/www/;
    index   index.html;
  }
  location /api {
    rewrite     ^(.*) $1 break;
    proxy_pass  http://carbon-api:4000/api/;
  }
}
```

I believe that this could easily be fixed as right now the docker images "as-is" are unusable.
A simple rewriting done by nginx (as provided above) could be easily included in the docker images.
