### ISSUE TITLE
No account show despite configured GCP project

### ISSUE THREAD

**Issue by antoinetran** [cloud-carbon-footprint/cloud-carbon-footprint#1373]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Operating System:**
  - 
  - Google Container OS
- **Browser:**
  - 
  - Firefox

### Expected Behavior

Cloudcarbonfootprint UI shows the configured GCP account

### Actual Behavior

No account is shown.

### To Reproduce

Deploys in GCP Kubernetes cluster this deployment (extract of a helm chart I wrote):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcarbonfootprint-api
  labels:
    app.kubernetes.io/name: cloudcarbonfootprint-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudcarbonfootprint-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudcarbonfootprint-api
    spec:
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
      - name: cloudcarbonfootprint-api
        image: {{ .Values.global.image.repository }}cloudcarbonfootprint/api:release-2024-05-11
        imagePullPolicy: Always
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets-gcp/service-account-keys.json"
        - name: GCP_BIG_QUERY_TABLE
          #value: "/secrets-gcp/GCP_BIG_QUERY_TABLE"
          value: "LISA_PROTO_CarbonFootprint_multi"
        - name: GCP_BILLING_PROJECT_ID
          #value: "/secrets-gcp/GCP_BILLING_PROJECT_ID"
          value: "project_id"
        - name: GCP_BILLING_PROJECT_NAME
          #value: "/secrets-gcp/GCP_BILLING_PROJECT_NAME"
          value: "project name"
        - name: GCP_PROJECTS
          #value: "/secrets-gcp/GCP_BILLING_PROJECT_NAME"
          value: '[{"id":"project_id","name":"project name"}]'
        ports:
        - containerPort: 4000
{{- with .Values.resources }}
        resources:
{{ toYaml . | nindent 10 }}
{{- end }}
        #tty: true
        volumeMounts:
          - name: vol-credentials-gcp
            mountPath: /secrets-gcp
            #subPath: service-account-keys.json
         #- name: vol-credentials-gcp
         #  mountPath: /run/secrets/service-account-keys.json
         #  subPath: service-account-keys.json
{{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 10 }}
{{- end }}
      volumes:
        - name: vol-credentials-gcp
          secret:
            secretName: cloudcarbonfootprint-gcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcarbonfootprint-client
  labels:
    app.kubernetes.io/name: cloudcarbonfootprint-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudcarbonfootprint-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudcarbonfootprint-client
    spec:
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
      - name: cloudcarbonfootprint-client
        image: {{ .Values.global.image.repository }}cloudcarbonfootprint/client:release-2024-05-11
        imagePullPolicy: Always
        ports:
        - containerPort: 80
{{- with .Values.resources }}
        resources:
{{ toYaml . | nindent 10 }}
{{- end }}
        #tty: true
        volumeMounts:
          - name: vol-nginx
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
{{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 10 }}
{{- end }}
      volumes:
        - name: vol-nginx
          configMap:
            name: cm-nginx

```

### Screenshots

![image](https://github.com/user-attachments/assets/cc8d1385-8265-444b-bbd6-9bfb40ae097f)

### Additional Information

Logs of API:
```
2024-08-16T14:21:13.500Z [api] info: Footprint API request started.
2024-08-16T14:21:13.507Z [Cache] info: Using local cache file...
2024-08-16T14:21:13.511Z [Cache] warn: Cache file not found. Creating new cache file...
2024-08-16T14:21:13.548Z [App] info: Starting AWS Estimations
2024-08-16T14:21:13.549Z [App] info: Finished AWS Estimations
2024-08-16T14:21:13.549Z [App] info: Starting GCP Estimations
2024-08-16T14:21:13.722Z [Compute Engine] warn: getCosts not Implemented. Called with start: Wed Aug 16 2023 00:00:00 GMT+0000 (Coordinated Universal Time), end: Fri Aug 16 2024 23:59:59 GMT+0000 (Coordinated Universal Time), region: us-east1
2024-08-16T14:21:13.725Z [Compute Engine] warn: getCosts not Implemented. Called with start: Wed Aug 16 2023 00:00:00 GMT+0000 (Coordinated Universal Time), end: Fri Aug 16 2024 23:59:59 GMT+0000 (Coordinated Universal Time), region: us-central1
2024-08-16T14:21:13.750Z [Compute Engine] warn: getCosts not Implemented. Called with start: Wed Aug 16 2023 00:00:00 GMT+0000 (Coordinated Universal Time), end: Fri Aug 16 2024 23:59:59 GMT+0000 (Coordinated Universal Time), region: us-west1
2024-08-16T14:21:15.956Z [App] info: Finished GCP Estimations
2024-08-16T14:21:16.150Z [auth] info: Authentication successful
2024-08-16T14:21:16.153Z [api] info: Regions emissions factors API request started
```

Logs of client:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
```

© 2021 Thoughtworks, Inc.
