### ISSUE TITLE
[SPIKE] Narrow down S3 permissions for ComputeOptimizerExportRole - LambdaPolicy

### ISSUE THREAD

**Issue by choweiyuan** [cloud-carbon-footprint/cloud-carbon-footprint#874]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/CONTRIBUTING.md) for this project.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

AWS - IAM & S3

I have deployed the following cloudformation - https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/cloudformation/ccf-compute-optimizer.yaml

Whilst this has worked, My company have a policy NOT to allow all actions to specific resource, e.g. s3:*

Specifically [
](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/cloudformation/ccf-compute-optimizer.yaml#L116-L122)
```
          - Action:
              - "s3:*"
            Effect: "Allow"
            Resource:
              - !Sub 'arn:aws:s3:::${BucketNamePrefix}-*'
              - !Sub 'arn:aws:s3:::${CentralBucketName}'
              - !Sub 'arn:aws:s3:::${CentralBucketName}/*'
```
It would be good to understand what are the s3 permissions that are actually required and limit the permissions needed for this role. It does seem a tad excessive to allow all.

### Expected Behavior

I would like to limit number of s3 actions allowed for the specified resources - to comply with least privilege access.

### Actual Behavior

LambdaPolicy used by ComputeOptimizerExportRole has been granted all s3 actions for the specified resources. 

### Screenshots

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/4201614/181480347-855feca8-8987-42a6-9db8-d6962d1620f5.png">

### Additional Information

© 2021 Thoughtworks, Inc.
