### ISSUE TITLE
[Question] Passing environment variable in Client package when using Docker image

### ISSUE THREAD

**Issue by jbdelpech** [cloud-carbon-footprint/cloud-carbon-footprint#980]
### Issue Details

Hello, I want to run both client and API in local environment with [docker-compose file](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/docker-compose.yml).

In my company, as we have large amount of data, we tried to configure client with environment variable in Docker image.

Based on [client package environment variables](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/client/.env.template), we tried to pass some of them, but it looks like environment variables are not taken into account in JS files.

### Expected Behavior
I use `REACT_APP_GROUP_BY` environment variable to override `groupBy` parameter when calling the API.

When connecting to client home page, here `http://localhost`, we expect to call the API with parameter `groupBy=month`:

`GET /api/footprint?start=2021-11-17&end=2022-11-17&ignoreCache=false&groupBy=month&limit=50000&skip=0`

### Actual Behavior

When connecting to client home page, here `http://localhost`, API calls are done with parameter `groupBy=day` (default values):

`GET /api/footprint?start=2021-11-17&end=2022-11-17&ignoreCache=false&groupBy=day&limit=50000&skip=0`

### To Reproduce

* Use the following [docker-compose file](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/docker-compose.yml). Add `env` section with any of [REACT Environment variable](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/client/.env.template):

```
...
services:
  client:
    image: cloudcarbonfootprint/client:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - REACT_APP_GROUP_BY=month
    depends_on:
      - api
...
```

* Run `docker-compose up`.
* Call `http://localhost` in browser or with curl.
* Watch client app logs OR browser network console to inspect the call to the API

### Additional Information

© 2021 Thoughtworks, Inc.
